server:
  host: 127.0.0.1
  port: 8080

grpc:
  host: 127.0.0.1
  port: 9879

mysqldatabase:
  user: root
  password: usersdatabase
  dbhost: 127.0.0.1
  dbport: 3306

crypt:
  secret: abc&1*~#^2^#s0^=)^^7%b34

environment: development