# environment

server:
  host: 127.0.0.1
  port: 8080

mysqldatabase:
  user: root
  password: employeedatabase
  dbhost: 127.0.0.1
  dbport: 3306

sqlitedatabase:
  path: ../development.db

environment: development